services:
  Jenkins-Service:
    container_name: Jenkins-Server
    image: jenkins/jenkins
    restart: always
    ports:
      -  8765:8080
    volumes:
      -  type: volume
         source: Jenkins-Data
         target: /var/jenkins_home
    networks:
      Jenkins-Network:
        ipv4_address: 10.100.0.20

volumes:
  Jenkins-Data: {}

networks:
  Jenkins-Network:
    driver: bridge
    ipam:
      config:
        -  subnet: 10.100.0.0/24
