services:
  Sonarqube-Service:
    container_name: Sonarqube-Container
    image: sonarqube
    ports:
      -  9000:9000
    volumes:
      -  type: volume
         source: Sonarqube-Data
         target: /opt/sonarqube/data
      -  type: volume
         source: Sonarqube-Plugins
         target: /opt/sonarqube/plugins
      -  type: volume
         source: Sonarqube-Extensions
         target: /opt/sonarqube/extensions
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    restart: none
    networks:
      Sonarqube-Network:
        ipv4_address: 10.90.0.10
    depends_on:
      -  postgres

  postgres:
    container_name: Postgres-Container
    image: postgres:14
    volumes:
      -  type: volume
         source: Postgres-Data
         target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      Sonarqube-Network:
        ipv4_address: 10.90.0.20

volumes:
  Sonarqube-Data: {}
  Sonarqube-Plugins: {}
  Sonarqube-Extensions: {}
  Postgres-Data: {}

networks:
  Sonarqube-Network:
    driver: bridge
    ipam:
      config:
        -  subnet: 10.90.0.0/24
